import {
  Decision,
  JsonObject,
  RunState,
  SopDefinition,
} from '@sop-runtime/definition';
import {
  applyDecision as applyCoreDecision,
} from '@sop-runtime/core';
import { RuntimeError } from './runtime_error.js';
import { HostDeps } from './runtime_host_types.js';
import { requireRunSnapshot, assertDefinitionMatchesRun, getCurrentAcceptedResult } from './runtime_host_state.js';
import { enforceMaxRunSecs } from './runtime_host_deadline.js';
import { Clock } from './clock.js';

/**
 * Decide an outcome for the current awaiting-decision step by outcome identifier.
 *
 * 根据结果标识符为当前 awaiting_decision 步骤做出决策。
 *
 * @param deps - The host dependencies.
 * @param definition - The SOP definition.
 * @param runId - The run identifier.
 * @param outcomeId - The outcome identifier to apply.
 * @param reason - Optional human-readable reason for the decision.
 * @param metadata - Optional structured metadata for the decision.
 * @returns The updated run state.
 * @public
 */
export async function decideOutcomeImpl(
  deps: HostDeps,
  definition: SopDefinition,
  runId: string,
  outcomeId: string,
  reason?: string,
  metadata?: JsonObject,
): Promise<RunState> {
  let { state, revision } = await requireRunSnapshot(deps.store, runId);
  assertDefinitionMatchesRun(definition, state);
  state = await enforceMaxRunSecs(definition, state, deps, revision);
  if (state.phase === 'terminated') return state;

  if (state.phase !== 'awaiting_decision') {
    throw new RuntimeError('invalid_runtime_state', {
      'message': 'Decisions can only be applied while the run is awaiting decision.',
      'details': {'phase': state.phase},
    });
  }

  const acceptedResult = getCurrentAcceptedResult(state);
  const decision: Decision = {
    'run_id': state.run_id,
    'step_id': acceptedResult.step_id,
    'attempt': acceptedResult.attempt,
    'outcome_id': outcomeId,
    'reason': reason ?? 'decided by agent',
    'metadata': metadata,
  };

  return applyDecisionAndEmit(deps, definition, state, decision, revision);
}

/**
 * Apply a decision (either provided or auto-generated by the DecisionProvider) to a run awaiting decision.
 *
 * 将决策（提供的或由 DecisionProvider 自动生成的）应用到 awaiting_decision 的运行。
 *
 * @param deps - The host dependencies.
 * @param definition - The SOP definition.
 * @param runId - The run identifier.
 * @param decisionOverride - Optional explicit decision to apply. If omitted, the DecisionProvider is called.
 * @returns The updated run state.
 * @public
 */
export async function applyDecisionImpl(
  deps: HostDeps,
  definition: SopDefinition,
  runId: string,
  decisionOverride?: Decision,
): Promise<RunState> {
  let { state, revision } = await requireRunSnapshot(deps.store, runId);
  assertDefinitionMatchesRun(definition, state);
  state = await enforceMaxRunSecs(definition, state, deps, revision);
  if (state.phase === 'terminated') return state;

  if (state.phase !== 'awaiting_decision') {
    throw new RuntimeError('invalid_runtime_state', {
      'message': 'Decisions can only be applied while the run is awaiting decision.',
      'details': {'phase': state.phase},
    });
  }

  const acceptedResult = getCurrentAcceptedResult(state);
  const decision = decisionOverride ?? await (async () => {
    const { signal, cleanup } = buildDeadlineSignal(definition, state, deps.clock);
    try {
      return await deps.decisionProvider.decide({
        'definition': definition,
        state,
        'accepted_result': acceptedResult,
        signal,
      });
    } finally {
      cleanup();
    }
  })();

  state = await enforceMaxRunSecs(definition, state, deps, revision);
  if (state.phase === 'terminated') return state;

  return applyDecisionAndEmit(deps, definition, state, decision, revision);
}

async function applyDecisionAndEmit(
  deps: HostDeps,
  definition: SopDefinition,
  state: RunState,
  decision: Decision,
  expected_revision?: string,
): Promise<RunState> {
  const nextState = applyCoreDecision({
    'definition': definition,
    state,
    decision,
    'now': deps.clock.now(),
  });
  await deps.store.saveRunState(nextState, { 'expected_revision': expected_revision });
  await deps.eventSink.emit({
    kind: 'decision_applied',
    'run_id': nextState.run_id,
    at: deps.clock.now(),
    details: {
      'step_id': decision.step_id,
      'attempt': decision.attempt,
      'outcome_id': decision.outcome_id,
    },
  });
  if (nextState.phase === 'terminated') {
    await deps.eventSink.emit({
      kind: 'run_terminated',
      'run_id': nextState.run_id,
      at: deps.clock.now(),
      details: {
        'run_status': nextState.terminal?.run_status ?? nextState.status,
        'reason': nextState.terminal?.reason ?? 'terminated',
      },
    });
  }

  return nextState;
}

/**
 * Build an AbortSignal that aborts when the run's max_run_secs deadline expires.
 *
 * 构建一个在运行的 max_run_secs 截止时间到期时中止的 AbortSignal。
 */
function buildDeadlineSignal(
  definition: SopDefinition,
  state: RunState,
  clock: Clock,
): { signal: AbortSignal; cleanup: () => void } {
  const controller = new AbortController();
  if (state.created_at === undefined) {
    return { 'signal': controller.signal, 'cleanup': () => {} };
  }

  const startedMs = Date.parse(state.created_at);
  const nowMs = Date.parse(clock.now());
  if (!Number.isFinite(startedMs) || !Number.isFinite(nowMs)) {
    return { 'signal': controller.signal, 'cleanup': () => {} };
  }

  const remaining = definition.policies.max_run_secs * 1000 - (nowMs - startedMs);
  if (remaining <= 0) {
    controller.abort();
    return { 'signal': controller.signal, 'cleanup': () => {} };
  }

  const handle = setTimeout(() => controller.abort(), remaining);
  return {
    'signal': controller.signal,
    'cleanup': () => { clearTimeout(handle); },
  };
}
